Ex webrtc integration test
fishjam-cloud/membrane_rtc_engine pull request #1
Opened 2024-09-19 07:52 UTC by roznawsk

2024-09-19 12:54 UTC, roznawsk commented on ex_webrtc/integration_test/test_videoroom/test/integration/basic_test.exs
> -                assert length(stats) == browser_id
fyi: Now each track is a separate stream, so the expected number of streams is double the number of peers

2024-09-19 12:55 UTC, roznawsk commented on ex_webrtc/test/ex_webrtc/track_sender_test.exs
> +    Pipeline.notify_child(pipeline, :track_sender, {:variant_bitrates, new_bitrates})
fyi: deprecated function in Membrane

2024-10-02 11:53 UTC, Karolk99 commented on ex_webrtc/lib/ex_webrtc_endpoint.ex
> +  end
i think this block needs some comment why it's written this way

2024-10-02 11:53 UTC, Karolk99 commented on ex_webrtc/test/ex_webrtc/peer_connection_handler_test.exs
> +  @track_metadata %{"server" => %{"displayName" => "mrwebrtc"}, "peer" => %{}}
🏎️

2024-10-10 14:11 UTC, Karolk99 requested changes

2024-10-11 07:59 UTC, roznawsk commented on ex_webrtc/lib/ex_webrtc_endpoint.ex
> +        keyframe_request_interval: Membrane.Time.seconds(3)
👍🏽

2024-10-11 08:01 UTC, roznawsk commented on ex_webrtc/lib/ex_webrtc/peer_connection_handler.ex
> +  def handle_parent_notification({:tracks_removed, track_ids}, _ctx, state) do
There is a task for this

2024-10-11 08:02 UTC, roznawsk commented on ex_webrtc/lib/ex_webrtc_endpoint.ex
> +    end
This will be done in separate PR, as discussed.

2024-10-11 10:21 UTC, Karolk99 approved these changes

2024-10-11 10:23 UTC, roznawsk commented
Dorime 🙏🏽

2024-10-11 10:23 UTC, merged