Add ex_webrtc_endpoint
fishjam-cloud/membrane_rtc_engine pull request #12
Opened 2024-10-29 15:17 UTC by roznawsk

2024-10-30 12:07 UTC, Karolk99 requested changes
I think we should remove WebRTC from this PR. We did last release with previous commit and we do not wish to support it further. All changes related to the WebRTC endpoint should be merged into a separate branch dedicated to WebRTC endpoint maintenance.

2024-10-31 09:56 UTC, roznawsk commented on engine/mix.exs
> +      {:membrane_core, "~> 1.0"},
Done

2024-10-31 10:24 UTC, roznawsk commented on ex_webrtc/integration_test/README.md
> +use of containerised headless browsers and containerised `test_videoroom` app.
Yes, this is the app that we use for integration tests

2024-10-31 10:26 UTC, roznawsk commented on ex_webrtc/internal_docs/assets/ex_webrtc_endpoint_architecture.drawio.svg
This is already updated

2024-10-31 10:27 UTC, roznawsk commented on ex_webrtc/internal_docs/protocol.md
Yes, the flow didn't change

2024-10-31 10:27 UTC, roznawsk commented on ex_webrtc/lib/metrics.ex
Currently we will have only non-RTP related metrics, such as Metadata updates

2024-10-31 10:31 UTC, roznawsk commented on examples/ex_webrtc_videoroom/README.md
Yes it does

2024-10-31 15:12 UTC, Karolk99 approved these changes

2024-10-31 15:12 UTC, Karolk99 commented on ex_webrtc/README.md
> +ExWebRTC Endpoint for the [Membrane RTC Engine](https://github.com/jellyfish-cloud/membrane_rtc_engine)
```suggestion
ExWebRTC Endpoint for the [Membrane RTC Engine](https://github.com/fishjam-cloud/membrane_rtc_engine)
```

2024-10-31 15:12 UTC, Karolk99 commented on ex_webrtc/README.md
> +- [React Native](https://github.com/jellyfish-dev/react-native-membrane-webrtc)
```suggestion
- [JS/TS](https://github.com/fishjam-cloud/membrane-webrtc-js)
- [Android](https://github.com/fishjam-cloud/membrane-webrtc-android)
- [iOS](https://github.com/fishjam-cloud/membrane-webrtc-ios)
- [React Native](https://github.com/fishjam-cloud/react-native-membrane-webrtc)
```

2024-10-31 15:12 UTC, Karolk99 commented on ex_webrtc/mix.exs
> +  @engine_github_url "https://github.com/jellyfish-dev/membrane_rtc_engine"
.

2024-10-31 15:20 UTC, Karolk99 commented on ex_webrtc/integration_test/test_videoroom/README.md
> +Test application for running integration against `membrane_rtc_engine` - specifically, the WebRTC
.

2024-10-31 15:34 UTC, Karolk99 commented on ex_webrtc/lib/metrics.ex
what about `Membrane.RTP.metrics`?

2024-10-31 15:36 UTC, Karolk99 reviewed
Generally there is a few requested changes and tests two tests fails

2024-11-04 11:17 UTC, roznawsk commented on ex_webrtc/integration_test/test_videoroom/README.md
> +## Testing scenarios
The scenarios have been updated (removed simulcast), others are same

2024-11-04 12:34 UTC, roznawsk commented on ex_webrtc/lib/metrics.ex
We don't use `membrane_rtp_plugin` so we don't have any RTP metrics. We should implement them, using the `ExWebRTC.PeerConnection.get_stats()` API

2024-11-04 12:40 UTC, roznawsk commented
Updated all occurences of `jellyfish-dev` and changed to `fishjam-cloud`. Added the project to codecov for coverage tracking. Updated badges for codecov and circleci.

2024-11-04 14:02 UTC, Karolk99 commented on ex_webrtc/lib/metrics.ex
We should sum up changes in metrics if either fishjam or cloud uses them. This way it'll be easier to adjust our cloud infrastructure to upcoming changes in membrane_rtc_engine.

2024-11-04 14:07 UTC, Karolk99 commented on ex_webrtc/README.md
> +ExWebRTC Endpoint for the [Membrane RTC Engine](https://github.com/jellyfish-cloud/membrane_rtc_engine)
.

2024-11-04 14:11 UTC, Karolk99 approved these changes

2024-11-04 14:25 UTC, merged